//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvcdress
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mall
    {
        public int Mall_id { get; set; }
        public string Mall_name { get; set; }
        public string dress_type { get; set; }
        public decimal dress_price { get; set; }
        public string dress_size { get; set; }
    }
}
